apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: vpn
  labels:
    app: nginx
    component: reverse-proxy
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP 