apiVersion: apps/v1
kind: Deployment
metadata:
  name: xray
  namespace: vpn
  labels:
    app: xray
    component: vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xray
  template:
    metadata:
      labels:
        app: xray
        component: vpn
    spec:
      containers:
      - name: xray
        image: teddysun/xray:latest
        imagePullPolicy: Always
        command: ["xray"]
        args: ["-c", "/etc/xray/config.json"]
        ports:
        - containerPort: 443
          name: vless
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          tcpSocket:
            port: 443
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 443
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config
          mountPath: /etc/xray/
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: xray-config
          items:
            - key: config.json
              path: config.json 