apiVersion: v1
kind: ConfigMap
metadata:
  name: xray-config
  namespace: vpn
data:
  config.json: |
    {
      "log": {
        "loglevel": "warning"
      },
      # DNS адрес берется из переменной окружения
      "dns": {
        "servers": [
          {
            "address": "${DNS_ADDRESS}"
          }
        ]
      },
      "inbounds": [
        {
          "port": 443,
          "protocol": "vless",
          "settings": {
            "clients": [
              {
                # UUID клиента берется из переменной окружения
                "id": "${ID}",
                "flow": "xtls-rprx-vision"
              }
            ],
            "decryption": "none"
          },
          "streamSettings": {
            "network": "tcp",
            "security": "reality",
            "realitySettings": {
              "show": false,
              "dest": "www.google.com:443",
              "xver": 0,
              "serverNames": [ "www.google.com" ],
              # Приватный ключ и короткий id берутся из переменных окружения
              "privateKey": "${PRIVATE_KEY}",
              "shortIds": [ "${SHORT_ID}" ]
            }
          }
        }
      ],
      "outbounds": [
        {
          "protocol": "freedom",
          "settings": {}
        }
      ]
    } 